### ISSUE TITLE
Exception when I set localZone and localDatacenter

### ISSUE THREAD

**Issue by marimcmurtrie** [Netflix/dyno#227]
I have Dynomite running in remote server. The cluster has 1 rack with 2 nodes.

In the Dynomite server,
```
curl -X GET maritest.abc.com:22222/cluster_describe
{"dcs": [{"name":"pnp","racks": [{"name":"rack1","servers": [{"name":"0.0.0.0","host":"0.0.0.0","port":8103,
"token":4294967294
},{"name":"127.0.0.1","host":"127.0.0.1","port":8101,
"token":2147483647
}]}]}]}
```

In Client side, I use DynoJedisClient. I supply my own HostSupplier and TokenMapSupplier.

```
Host host = new Host("maritest.abc.com", null, 8102, "rack1", "pnp", Host.Status.Up);
HostSupplier customHostSupplier = new HostSupplier() {
            @Override
            public List<Host> getHosts() {
                return Collections.singletonList(host);
            }
        };

String tokenMapJson = "
[{
 	\"token\": \"2147483647\",
 	\"hostname\": \"maritest.abc.com\",
 	\"zone\": \"rack1\",
 	\"dc":\ "pnp\"
 }, {
 	\"token\": \"4294967294\",
 	\"hostname\": \"maritest.abc.com\",
 	\"zone\": \"rack1\",
 	\"dc\": \"pnp\"
 }]
";
TokenMapSupplier tokenSupplier = new AbstractTokenMapSupplier() {
            @Override
            public String getTopologyJsonPayload(Set<Host> set) {
                return tokenMapJson;
            }
            @Override
            public String getTopologyJsonPayload(String hostname) {
                return tokenMapJson;
            }
        };
```

Then I instantiate DynoJedisClient

```
 dynoClient = new DynoJedisClient.Builder()
                .withApplicationName(appName)
                .withHostSupplier(customHostSupplier)
                .withTokenMapSupplier(tokenSupplier)
                .build();
```

In log, I get these warnings

> WARN  [2018-06-25 15:05:58,542] com.netflix.dyno.jedis.DynoJedisClient: DynoJedisClient for app=[webproxy] is configured for local rack affinity but cannot determine the local rack! DISABLING rack affinity for this instance. To make the client aware of the local rack either use ConnectionPoolConfigurationImpl.setLocalRack() when constructing the client instance or ensure EC2_AVAILABILTY_ZONE is set as an environment variable, e.g. run with -DEC2_AVAILABILITY_ZONE=us-east-1c [main]
WARN  [2018-06-25 15:05:58,550] com.netflix.dyno.connectionpool.impl.lb.AbstractTokenMapSupplier: Local Datacenter was not defined [main]

So I added those 2 variables before I instantiate DynoJedisClient.

 ```
       System.setProperty("EC2_REGION", "pnp");
       System.setProperty("EC2_AVAILABILITY_ZONE", "rack1");
```
If I supply the above 2 variables, I get an Exception.

In Log
> ERROR [2018-06-25 14:05:32,080] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 4ec7ab819b9ca7eb [dw-51 - GET /redis/allkeys]
! com.netflix.dyno.connectionpool.exception.PoolOfflineException: PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down, hashtag=null], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
! at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnection(HostSelectionWithFallback.java:163)
! at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.getConnectionsToRing(HostSelectionWithFallback.java:256)
! at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.executeWithRing(ConnectionPoolImpl.java:366)
! at com.netflix.dyno.jedis.DynoJedisClient.d_keys(DynoJedisClient.java:2663)
! at com.netflix.dyno.jedis.DynoJedisClient.keys(DynoJedisClient.java:2643)

In Console

> java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4059)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.createConnectionPool(DynoJedisClient.java:4031)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:4007)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3936)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.calculateReplicationFactor(HostSelectionWithFallback.java:396)
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.initWithHosts(HostSelectionWithFallback.java:353)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.initSelectionStrategy(ConnectionPoolImpl.java:627)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:526)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4042)

**Comment by marimcmurtrie** [comment]
In short, if I don't set "EC2_REGION" and "EC2_AVAILABILITY_ZONE", I got warning but it works. If I set those, then I get Exception. I think I should set these 2 variables (code seems to expect those 2 set) but I do not want Exceptions, of course.
Something is off here, that I cannot find out. I appreciate your help.

**Comment by shailesh33** [comment]
ok. I think the problem is it is trying to calculate the replication factor and cannot find more than one rack.
Rather it assumes it will have more than 1 rack and hence the exception. digging more in the code

**Comment by shailesh33** [comment]
wondering why host name is same for both the hosts and also why you are not providing 2 hosts in the host supplier.

**Comment by marimcmurtrie** [comment]
Do I have to host each node separately? I have those 2 nodes in the same server (hence, the same host name). 
Also, @ipapapa told me that I need only 1 Host object in a list returned via HostSupplier. 
These relationships of nodes and hosts are not clear in the doc. Also, there is an assumption that you are familiar to a certain set up (e.g. AWS). I do not know anything about AWS so things are not clear for me. I really appreciate your help.

**Comment by ipapapa** [comment]
Are you using the Dyno from the master branch? Some exception lines do not fully match.

**Comment by marimcmurtrie** [comment]
Hi, I use it from Maven - https://mvnrepository.com/artifact/com.netflix.dyno/dyno-jedis
I am not at work now but I believe I got the latest stable. Thank you!

**Comment by ipapapa** [comment]
Would it be easy to use the latest version (which is an RC)?

**Comment by ipapapa** [comment]
The version is solid, it has tested fairly well. We use RC versions for our internal customers to use them. If we deployed a stable that would affect all Dynomite use cases and we don't want to do that (think about it like canary testing version).

**Comment by marimcmurtrie** [comment]
I updated to 1.6.4-rc2. The exception still happens. Here is the error message in stdout.

```
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4066)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.createConnectionPool(DynoJedisClient.java:4038)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:4014)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3943)
	at com.soundhound.lookupservice.cache.client.DynoCacheClient.<init>(DynoCacheClient.java:92)
	at com.soundhound.lookupservice.config.CacheFactory.build(CacheFactory.java:83)
	at com.soundhound.lookupservice.WebProxyService.run(WebProxyService.java:57)
	at com.soundhound.lookupservice.WebProxyService.run(WebProxyService.java:31)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:93)
	at com.soundhound.lookupservice.WebProxyService.main(WebProxyService.java:40)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.calculateReplicationFactor(HostSelectionWithFallback.java:414)
	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.initWithHosts(HostSelectionWithFallback.java:362)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.initSelectionStrategy(ConnectionPoolImpl.java:626)
	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:528)
	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:4049)
	... 12 more

```

**Comment by marimcmurtrie** [comment]
Here is my Dynomite cluster. I have 2 racks, each rack has 1 node.

**redis_rack1_node_mari.yml in maritest.abc.com (216.22.222.2)**
```
dyn_o_mite:
  datacenter: dc
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 216.11.111.1:8101:rack2:dc:1383429731
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6379:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  read_consistency : DC_SAFE_QUORUM
  write_consistency : DC_SAFE_QUORUM
  stats_listen: 0.0.0.0:22221
```
**redis_rack2_node_mari.yml in maritest.zzz.com (216.11.111.1)**
```
dyn_o_mite:
  datacenter: dc
  rack: rack2
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - 216.22.222.2:8101:rack1:dc:1383429731
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:6377:1
  tokens: '1383429731'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  read_consistency : DC_SAFE_QUORUM
  write_consistency : DC_SAFE_QUORUM
  stats_listen: 0.0.0.0:22222
```

My Dyno client code
**json for Token map** 

```
[{
	"token": "1383429731",
	"hostname": "maritest.abc.com",
	"zone": "rack1",
	"dc": "dc"
}, {
	"token": "1383429731",
	"hostname": "maritest.zzz.com",
	"zone": "rack2",
	"dc": "dc"
}]
```
**hosts List for getHosts()** 
```
[Host [hostname=maritest.abc.com, ipAddress=null, port=8102, rack: rack1, datacenter: dc, status: Up, hashtag=null], 
Host [hostname=maritest.zzz.com, ipAddress=null, port=8102, rack: rack2, datacenter: dc, status: Up, hashtag=null]]
```
Code snippets
```
      //If I comment out below 2 line, code works. If uncomment, Exception is thrown.
      System.setProperty("EC2_REGION", "dc");
      System.setProperty("EC2_AVAILABILITY_ZONE", "rack1");

      HostSupplier customHostSupplier = new HostSupplier() {
            @Override
            public List<Host> getHosts() {
                return hosts; //See above for the actual value
            }
        };

        final String tokenMapJson = tokenMapArrayNode.toString();
        TokenMapSupplier tokenSupplier = new AbstractTokenMapSupplier() {
            @Override
            public String getTopologyJsonPayload(Set<Host> set) {
                return tokenMapJson; //See above for actual value
            }
            @Override
            public String getTopologyJsonPayload(String hostname) {
                return tokenMapJson;
            }
        };

        dynoClient = new DynoJedisClient.Builder()
                .withApplicationName("myApp")
                .withHostSupplier(customHostSupplier)
                .withTokenMapSupplier(tokenSupplier)
                .build();
```

**Comment by marimcmurtrie** [comment]
I think this was related to Token Map or Host Map. I no longer see the exception after I changed my code a bit.

**Comment by shl1988012** [comment]
if has 2 dc ,how code write ? 
when I user only a 'get' operation, It repeat lots of message:WARN  c.n.d.c.i.l.AbstractTokenMapSupplier - Local Datacenter was not defined for many times.

**Comment by Kevzz81517** [comment]
@ipapapa Do we need to provide the tokenmap and hostsupplier, if we are using the .withDiscoveryClient(eurekaClient) ?

**Comment by abhinav0101** [comment]
@marimcmurtrie What Data Center do we need to specify inside localDataCenter
